### ISSUE TITLE
chrome.webRequest exceptions when listening on events :(

### ISSUE THREAD

**Issue by dylanPowers** [dart-gde/chrome.dart#213]
It appears that the proper arguments aren't being passed. In the [documentation](https://developer.chrome.com/extensions/webRequest) it's mentioned that a ["filter"](https://developer.chrome.com/extensions/webRequest#type-RequestFilter) is required that at the very least must have a _urls_ property defined.

This is the exception I get when I try to run onBeforeRequest.listen(data => print(data))
```
Exception: Uncaught Error: Error: Parameter 1 (filter) is required.
Stack Trace:
#0      JsObject._callMethod (dart:js:235)
#1      JsObject.callMethod (dart:js:225)
#2      _ensureHandlerAdded (package:chrome/src/common.dart:176:23)
#3      _runGuarded (dart:async/stream_controller.dart:669)
#4      _BroadcastStreamController._subscribe (dart:async/broadcast_stream_controller.dart:199)
#5      _ControllerStream._createSubscription (dart:async/stream_controller.dart:687)
#6      _StreamImpl.listen (dart:async/stream_impl.dart:474)
#7      main (chrome-extension://obaakcmlgkhenfocgiedogghmbencagi/main.dart:6:36)
```

**Comment by apaulus** [comment]
I'd like to bump this. This is the only way to make a web request fom a dart chrome packaged app, right? So because of this issue we cannot make any web requests? This is really bad :/
